### ISSUE TITLE
[Epic] - Evolve Pizza-Order-Showcase 

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#3]
- [x] Description created
- [x] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
This epic sums up all tasks which needs to be done to deliver a talk at the Camunda Community Summit. During this effort the pizza-order-showcase needs to be changed in such a way that it can be used for a talk.  

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] #4 
- [ ] #5
- [ ] #6 
- [ ] #7
- [ ] #8 
```

## Stakeholder
* @DaAnda97 
* @Hafflgav 

# Acceptance
When a talk with a streamlined story can be created out of the showcase.

**Comment by DaAnda97** [comment]
This epic is very well defined and ready to work on.
